### ISSUE TITLE
What is the role of the BaseInteractorWorker or BaseInteractor 

### ISSUE THREAD

**Issue by imzyf** [adimango/insights-for-instagram#3]
hi Alex, thanks to share your project. I am a new iOS developer. I don't understand What is the role of the `BaseInteractorWorker` or `BaseInteractor` ?

Is it MVP design pattern?

**Comment by adimango** [comment]
Hi,
no it's not MVP, the app follow the clean architecture principles. 
Here a good reference: https://clean-swift.com/clean-swift-ios-architecture/
That will help you to understand the main actors. 

I hope it will help.
Alex

**Comment by imzyf** [comment]
Thanks Alex.

It's very useful.
