### ISSUE TITLE
[Question] - Media insights usernames

### ISSUE THREAD

**Issue by ghost** [adimango/insights-for-instagram#4]
Is it possible to get a list of what users who liked my posts, and who is following me?

**Comment by adimango** [comment]
Yes, it is possible but currently the endpoints are not public.
I will soon release a new api version with more endpoints available.

Alex

**Comment by xScylez** [comment]
@adimango That sounds awesome! I guess you can use the list of who liked my posts, to find who does not like my posts of the people is following me, to see "ghost followers"? Do you think you can add a option for that as well? And when do you think you will release the new API? :) Love the work you do btw!

**Comment by ghost** [comment]
That sounds awesome, I like the work you do! I guess you can use the list of who liked my posts, to find who does not like my posts of the people is following me, to see "ghost followers"? Do you think you can add a option for that as well? And when do you think you will release the new API with more endpoints? :)
