### ISSUE TITLE
Server side API open sourced?

### ISSUE THREAD

**Issue by salverde** [adimango/insights-for-instagram#6]
Hey man loving this code base! super clean and I had never heard of Moya! Nifty.

However, I'd like to be able to rely on your API, is it forkable? https://insights-for-instagram.herokuapp.com
You briefly mention its graphql based? Interested in this gateway to IG

**Comment by salverde** [comment]
@adimango ^^^?

**Comment by adimango** [comment]
Hi salsyds, it is not public and not really stable.. i"m sorry
